[package]
name = "phobos-companion"
version = "1.0.1"
edition = "2021"
description = "Lightweight Windows companion proxy for Phobos WireGuard protocol"

[dependencies]
flate2 = "1.0"
tar = "0.4"
rand = "0.8"
crc32fast = "1.4"
boringtun = "0.7.1"
wintun = "0.5.1"
base64 = "0.23.1"
ctrlc = "3.5.2"
zeroize = { version = "1.8", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_UI_Controls_Dialogs",
    "Win32_UI_Shell",
    "Win32_UI_HiDpi",
    "Win32_Security_Cryptography",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_LibraryLoader",
    "Win32_System_Console",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
